### ISSUE TITLE
Cursor Composer support

### ISSUE THREAD

**Issue by kyleli626** [gait-ai/gait#65]
since composer chats are now persistent, capture them in gait

**Comment by tfriedel** [comment]
yes please. I was actually enthusiastic about trying gait, but I mostly use composer. Noticed gait currently doesn't work for me because of that.

**Comment by kyleli626** [comment]
They just added persistence this week - we're on it

**Comment by kyleli626** [comment]
hey @tfriedel @MyJumperBroke23 merged yesterday! Let us know what you think :)

**Comment by tfriedel** [comment]
@kyleli626 Thanks!
I've tried it again. It didn't detect any chats when I used composer.
To figure out if it was related to composer I wanted to try regular chats. So I then created a regular chat in the sidebar, asked it to add some docstrings to a function. But also that didn't register.

**Comment by tfriedel** [comment]
It doesn't automatically update the extension. If select "Install Specific Version..." and then v0.0.11 (from 1 hour ago) I get an error:
 Unable to install extension 'gait.gait' because the requested version '0.0.11' is not found.
 
 The regular chat was not working even after letting Cursor open for hours and then checking back later.

**Comment by kyleli626** [comment]
Hmm sorry about that!!! It takes a bit for the cursor extension marketplace to update. Try https://www.cursor.com/how-to-install-extension

https://marketplace.visualstudio.com/items?itemName=gait.gait

You might have to download extension.

Regarding the regular chat - that must be frustrating. So it's not in staged chats or unstaged chats in the panel? Could you let me know what version of cursor your on? Hopefully installing the newest version should fix.

**Comment by tfriedel** [comment]
Ok I was able to upgrade using the download. However I still don't see any chats in gait, neither from composer nor chat.

I believe I have the newest Cursor:
Version: 0.42.3
VSCode Version: 1.93.1
Commit: 949de58bd3d85d530972cac2dffc4feb9eee1e40
Date: 2024-10-16T17:56:07.754Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

The project is using WSL in Windows. I also was trying it with Remote SSH before.

**Comment by kyleli626** [comment]
@tfriedel 

Thanks for the detail and bug report! We suspect this might be something with windows, we are on macOS - will get on that tonight.

**Comment by kyleli626** [comment]
@tfriedel apologies for the delay! We believe the current version fixes this issue for windows. Thanks @OmkarBansod02 for the help with debugging. Thanks again for your patience with us!

**Comment by tfriedel** [comment]
sorry, it's still not working (v 0.0.13)

**Comment by kyleli626** [comment]
Followed up to debug separately
